### ISSUE TITLE
Referral Booster => Create Voucher Program (50%/50%)

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#10]
We give voucer that reduce price for x sessions for both parties:
- the participant who found a new participant
- the new participant
  in 50% / 50%

We create flyers that only reduce the price for the person we give it to:
- reciepient of voucher gets everything, its just given by us (as a business card)

**Comment by serapath** [comment]
# "Voucher Program"

We offer each kid and/or their parents, to find some more kids who would be interested to learn programming. That would be great, because it also makes it easier for us to organize collaborative projects, where kids work together on some kind of game or application.

## It works as follows:
- Each new kid (brought in through someone who already joined the school) will get `50% OFF` for one month, but so will the kid through which the new one came in, thus:
  - e.g. `Kid X` brings in four friends (If `Kid X` brings in more friends, it accumulates)
  - => `Kid X` (`50% OFF` for four month) **OR** (`100% OFF` for the next two months)
  - **In addition:** Each kid gets `10% OFF` permanently for as long as those friends continue to stay with us
