### ISSUE TITLE
Create Funding Campaign

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#12]
- [ ] Sponsors (Github, RasberryPie...)
- [ ] Celebrity sponsors (big names, politicians etc.)
- [ ] Community - (CoUp etc.)

**Comment by ninabreznik** [comment]
LINKS
- https://medium.com/@nearform/nearform-shares-its-practical-commitment-to-community-53aeaedc8774

**Comment by ninabreznik** [comment]
**Free Workshops -> Sponsorships -> Scholarships for kids**

We are planning some **free workshops for kids** in the next weeks, would like to also do some co-branding with Rails Girls and NodeSchool and CoUp and  to make some photo material so we could approach sponsors & hopefully start earning some money and enable scholarships for kids with it. 

Coding classes are in both - **german and english**. Of course kids a re not so good in english yet, so we do it in german but combining with english so they can learn both - programming and improve their english (plus if there are international kids who are not good in german, they can be sure, they will be able to speak english).

**Laptops** - kids bring them from their parents so this for now shouldn't be a problem because for coding you don't need a super powerful computer. If kids will need computers, maybe it would be smart to ask Tessl or Raspberry Pie for sponsorship and bring in those micro computers and then attach them to CoUp's monitors and keyboards so we stay minimal.

**Pay the mentors** - we want to pay mentors for teaching so this is why we want to find sponsors for. Our idea is to find mentors who are themselves learners and pay them to continue learning by teaching kids. It is very hard to continue learning programming so we don't want learners to just give up on but instead be self employed, work on smaller projects and earn also a bit from teaching kids.
