### ISSUE TITLE
Codemotion Event

### ISSUE THREAD

**Issue by ninabreznik** [wizardamigosinstitute/organisation#24]
- [ ] logo (old guy + funky kids - mashup of old and new logo) - Nina
- [ ] promo material 
- wizard baloons, 
-  tear-of flyers (some only with wizard, some with kids)
  - 10 in colour with plastic wrap for indoor  
  - 100 b&w outdoor
- [ ] offline games
- Binary magician game (we need black&white cards-stickers)
- Orange game (we need baloons (flour, baloons), 
  hats http://4.bp.blogspot.com/-Nt9MTuQ4Dhg/Uoldo7QXKvI/AAAAAAAApx8/OCnECY6P91k/s1600/DSC_0454.JPG, 
  capes (towels + blankets)
- Cup pyramid game (we need commands on the paper+blank papers & pens) http://splash.abc.net.au/home#!/media/1608979/learning-programming-offline
- [ ]  prints (sticker, rollup display)
- [ ] gadgets (cardboard, helicopter, raspberry pie)
- [ ] Wizard area decoration (find boxes + wrapping paper -> cut cubes and make pixelated boxes)
- [ ] apples (instead of candies)

**Comment by serapath** [comment]
# Codemotion Event - Email History


**Am Mon, Oct 12, 2015 at 10:52 AM schrieb Linda Dudacy:**

Hi Alex,

do you have any feedback concerning our Codemotion Kids - area? I hope you are still interested in joining the conference and organize a little kids-program.

May I help you in any preparations?

Best wishes,
Linda


---


**Am 29.09.2015 um 13:33 schrieb Linda Dudacy:**

Hi Alex,

so maybe let's schedule the kids-program to 11:00 - 15:00 every day? 

I'm  totally excited about what your planning to do with the Codemotion-kids. As I said it already, we will provide a blogpost with all information about the "kids program" and with requirements (computers). Just one question: That program will by performed by you or more people? What do you think about announcing it this week (maybe Tuesday)?

Moreover we collect some ideas for making Codemotion more community-based and creative. I had the idea to print out codes, made by kids and arrange a wall in the communityspace (maybe directly at the kids-area) with the prints. What do you think about that, or do you have other ideas? We are really open to proposals. Therefore we would need your help. Either you have codes from passed workshops or we make a "Call", maybe with a award or something like that.

Thanks a lot.
Best,
Linda



---


**Am 26.09.2015 um 00:03 schrieb Wizard Amigos (Alex):**

Hey Linda,

so it's basically 4 hours or 2 x 2 hours. If kids don't have computers they cannot do anything, but maybe just watch something we present.
If they bring computers - depending on their pre-knowledge, which is probably not a lot - the best thing to do in 4 hours would maybe to let them play a programming game.

So we would maybe be around and show them codecombat.com and let them play some levels :-)
That's our idea to maybe get them excited and actually do something with real code.

---

**On Fri, Sep 25, 2015 at 10:42 AM, Linda Dudacy**

Hi Alex,

sorry for my late reply.
I think the most complicated fact is, that we really do not know anything about potential audience. This is the second Codemotion here in Berlin and we have no feedback about Codemotion kids 2013.

I have no response from the other two potential kids-workshops. So I would suggest we have to start with planning the two days. You will have a "separate" area in our community-area at Frannz Club. We will provide tables and chairs for approx. 10-15 kids (more like a lounge and not that strict). Furthermore I think it would be great to have a little program structure like: from 10 to 12 and from 14 to 16 over the two days. In general this should be something like an offer for kids, not a full-time childcare. What do you think about that?

Maybe we always can start in the morning with something for beginners and than "upgrade"? I really like the ideas like the videos or the programming games. That would be a great offer for our Codemotion kids! What do you need for that? I'm afraid, but we could not provide that much extras like laptops or anything like that. Like for all the other workshops I think it would be no problem to expect, that the kids should bring on their own laptop. Or how to you handle that? 

I really would like to publish the Codemotion-kids-offering, so we have to fix the frameworks. Moreover I will need a little abstract about what you are planning to do. All in all you are really free to do whatever you think will be well received. 

How much free-tickets do you need? In general, every community will get 2-4 free-tickets. And we have a 20%-Discount Code for all community-members you can spread through internally mailinglists or newsletters: Community_Discount_Cjioe83ogk4

Thanks a lot in advance and please let me know how I can support you!

Best wishes,
Linda


---

**Am 15.09.2015 um 03:53 schrieb Wizard Amigos (Alex):**

Yes, that would be great to invite the other 1-2 kids workshop requests in :-)
We have our regular "school curriculum", but what can be done in a short time to introduce people how have no clue for the first time - i dont know :-)
We have some ideas, but we're open for suggestions and would like to learn more about the potential audience and their age and pre-knowledge.
(e.g. typing speed, english literacy, ...)

Maybe some inspirational videos about how the near future will look like in which a lot of things get automated, that could be AI, robots, drones, and effects on all kinds of life aspects
Another one could be playing programming games given that they or we have enough laptops or computers. Some games that teach programming are available on smartphones and tablets too.
There are some "offline games" that teach basic concepts and how to think like a programmer

...probably there is a lot more :-)


---

**On Mon, Sep 14, 2015 at 8:51 AM, Linda Dudacy**

Hi Nina,

I will send you a plan of the community area tommorrow where I will mark the possible kids space for you.

Could you give me a short overview what will happen there and how much "progam" you are planning to provide? Of course Codemotion is for free for kids. Means "leaners" that the workshops or stuff is leading by kids or do you just mean the young Codemotion attendees? Moreover I have in mind,that we have 1-2 other requests for kids workshops. Should we include them or make a mixture of yours and other workshops?

I'm really looking forward it! Could you provide a little abstract so that we can provide a blogpost and start promoting officially CODEMOTION KIDS? :) Thanks for allready sharing the event! 

Best regards,
Linda 

---

**Am Donnerstag, 10. September 2015 schrieb Wizard Amigos (Nina) :**

Awesome. Looking forward to this.

Do you have any idea how the place where we will be, will look like, just to imagine what would be smart to prepare as our promotion material and for the cozyness in the area;)

And one more thing - is event free for kids? If so, we could then also invite our learners and their kid friends ;)

Thanks in advance!

PS: Already sharing the event on Fb and stuff :)

---

**On Thu, Sep 10, 2015 at 5:27 PM, Linda Dudacy**

Hi Nina,

welcome to Codemotion Berlin 2015! Your are already on our website: http://berlin2015.codemotionworld.com/partners/communities/

I will ask our communication team about github etc. and will let you know about this! Maybe you can send me the workshop-abstact at the beginning of the next week? That would be great, we will provide a blogpost article.

Thanks again for your quick response!

Best wishes,
Linda

---

**Am 10.09.2015 um 17:16 schrieb Wizard Amigos (Nina):**

Hey, Linda,

good idea to switch to email:) So here we go.

I am also sending you links to our FB, Twitter and our webpage.
https://www.facebook.com/wizardamigos
https://twitter.com/wizardamigos
wizard.amigos.institute

And in the attachment you will find our logo.

PS: Are you maybe planning your event somewhere public, where we could follow discussion (like Github, Gitter etc.)?

-- 
Cheers,
Nina

**Comment by serapath** [comment]
http://csunplugged.org/videos/

**Comment by serapath** [comment]
https://www.druck-und-display.de/rollup-displays/rollup-standard.html?gclid=CLeBs7brv8gCFQ2NGwodX94Axw
